pipeline {
       agent any
               stages {
                   stage('clone project') {
                             steps {
                                git branch:'master' ,
                                url:'https://github.com/sivalakkireddy9/Amazon-Ecom'
                                    }
                                }
                
               stage('build') {
                                   steps {
                                       sh 'mvn clean install'
                                           }
                                     }
                     }
    }
